import { News, Earthquake } from "./types/types";

export const news: News[] = [
  {
    id: "1",
    title: "İzmir'de 5.2 Büyüklüğünde Deprem",
    snippet: "İzmir'de meydana gelen deprem çevre illerde de hissedildi.",
    content:"3 Haziran 2025’te sabaha karşı saat 02:17’de Akdeniz’in Muğla Marmaris açıklarında 5,8 büyüklüğünde meydana gelen deprem, yaklaşık 68 kilometre derinlikte gerçekleşti; sarsıntı Antalya’dan İzmir’e kadar geniş bir alanda hissedilirken, Marmaris’te duvar çatlakları ve eşya devrilmeleri yaşandı, 14 yaşındaki Afranur Günlü hayatını kaybederken 69 kişi yaralandı ve mobil sağlık ekipleri ile psikolojik destek hatları devreye sokuldu; AFAD, UMKE, jandarma ve gönüllülerden oluşan 150 kişilik arama-kurtarma ekibi 24 saat esasına göre hasar tespiti ve enkaz taraması yaparken, İçişleri ve Ulaştırma Bakanlıkları krizi koordine edip alternatif güzergâhlar oluşturdu; uzmanlar artçı sarsıntıların birkaç gün sürebileceğini, deniz kenarında teknelerin kontrollerinin yapılmasını ve vatandaşların açık alanlarda kalmalarını önerirken, yerel halk sosyal medyada bilgileri paylaşarak okullar ve spor salonlarını geçici barınma alanı olarak kullanmaya başladı.",
    image: "https://www.rudaw.net/s3/rudaw.net/ContentFiles/871171Image1.jpg?version=7666282",
    created_at: "2025-06-27T08:32:00Z",
    category: ["latest", "experts"],
    source: "AFAD",
  },
  {
    id: "2",
    title: "Şiddetli Fırtına İstanbul’u Vurdu",
    snippet:
      "İstanbul'da akşam saatlerinde etkili olan fırtına ağaçları devirdi.",
    content:
      "İstanbul'da yaşanan şiddetli fırtına nedeniyle bazı bölgelerde ağaçlar devrildi, çatı uçmaları yaşandı. Yetkililer, vatandaşları dikkatli olmaları konusunda uyardı.",
    image: "https://www.indyturk.com/sites/default/files/styles/1368x911/public/article/main_image/2022/09/06/1005476-559994866.jpg?itok=rjXWEv_g",
    created_at: "2025-06-26T19:55:00Z",
    category: ["latest"],
    source: "CNN Türk",
  },
  {
    id: "3",
    title: "Ankara’da Sel Felaketi: 2 Kişi Hayatını Kaybetti",
    snippet: "Ankara'da aniden bastıran yağış sel felaketine yol açtı.",
    content:
      "Ankara'da öğle saatlerinde başlayan şiddetli yağış, kısa sürede sele dönüştü. İki kişi hayatını kaybederken, birçok ev ve iş yeri zarar gördü.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-25T14:20:00Z",
    category: ["latest", "analysis"],
    source: "NTV",
  },
  {
    id: "4",
    title: "Ekonomi Zirvesi İstanbul’da Başladı",
    snippet: "Yerli ve yabancı yatırımcılar İstanbul’da bir araya geldi.",
    content:
      "İstanbul’da düzenlenen Ekonomi Zirvesi’nde, finans dünyasının önde gelen isimleri küresel ekonomi ve Türkiye'nin yatırım fırsatları hakkında görüş alışverişinde bulundu.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-25T09:00:00Z",
    category: ["experts", "analysis"],
    source: "Bloomberg HT",
  },
  {
    id: "5",
    title: "Van’da Deprem: Can Kaybı Yok",
    snippet: "Van’da 4.1 büyüklüğünde deprem meydana geldi.",
    content:
      "Van'ın Tuşba ilçesinde 4.1 büyüklüğünde deprem yaşandı. İlk belirlemelere göre can kaybı veya yaralanma olmadı.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-24T22:11:00Z",
    category: ["latest", "experts", "analysis"],
    source: "AFAD",
  },
  {
    id: "6",
    title: "Yapay Zekâ ile Deprem Tahmini Mümkün mü?",
    snippet:
      "Bilim insanları, yapay zekâ ile deprem tahmininde yeni adımlar atıyor.",
    content:
      "Dünyada ve Türkiye'de yapay zekâ kullanılarak deprem tahmini çalışmaları hız kazandı. Uzmanlar, erken uyarı sistemlerinin geliştirilmesi için büyük veri analizi kullanıyor.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-24T17:40:00Z",
    category: ["experts", "analysis"],
    source: "BBC",
  },
  {
    id: "7",
    title: "Dünya Sağlık Örgütü’nden Sıcak Hava Uyarısı",
    snippet: "Avrupa’da rekor sıcaklıklar bekleniyor.",
    content:
      "DSÖ, Avrupa'da önümüzdeki hafta beklenen aşırı sıcaklıklara karşı vatandaşları uyardı. Uzmanlar, yaşlılar ve çocukların dikkatli olmasını öneriyor.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-23T12:00:00Z",
    category: ["latest"],
    source: "BBC",
  },
  {
    id: "8",
    title: "Teknoloji Zirvesi’nde Gündem: Afet Yönetimi",
    snippet: "Teknoloji dünyası afetlere karşı çözümler geliştiriyor.",
    content:
      "İstanbul'daki Teknoloji Zirvesi’nde afet yönetimi, deprem erken uyarı sistemleri ve dijitalleşme ana gündem oldu.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-22T16:10:00Z",
    category: ["experts"],
    source: "Webrazzi",
  },
  {
    id: "9",
    title: "Kandilli Rasathanesi’nden Marmara Depremi Açıklaması",
    snippet: "Kandilli’den Marmara Bölgesi için önemli açıklama.",
    content:
      "Kandilli Rasathanesi uzmanları, Marmara Bölgesi'nde olası bir büyük depremin hazırlıkları konusunda kamuoyunu bilgilendirdi.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-21T10:00:00Z",
    category: ["experts", "analysis"],
    source: "Kandilli Rasathanesi",
  },
  {
    id: "10",
    title: "Türkiye Milli Takımı Çeyrek Finalde",
    snippet: "A Milli Futbol Takımı çeyrek finale yükseldi.",
    content:
      "EURO 2024’te mücadele eden Türkiye Milli Takımı, rakibini mağlup ederek çeyrek finale yükseldi.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-20T22:50:00Z",
    category: ["latest"],
    source: "NTV Spor",
  },
  {
    id: "11",
    title: "Küresel Isınma: 2025 Yazı Rekor Sıcaklıklarla Geçebilir",
    snippet: "Bilim insanlarından rekor sıcaklık uyarısı.",
    content:
      "Küresel ısınma nedeniyle 2025 yılının yaz aylarında sıcaklıkların rekor seviyelere çıkabileceği açıklandı.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-20T14:37:00Z",
    category: ["experts", "analysis"],
    source: "BBC",
  },
  {
    id: "12",
    title: "Depremde Hayat Kurtaran 10 Önlem",
    snippet: "Uzmanlardan deprem öncesi ve sonrası için öneriler.",
    content:
      "Uzmanlar, deprem öncesinde ve sırasında alınabilecek önlemlerle birçok hayatın kurtarılabileceğini belirtiyor. İşte en önemli 10 öneri...",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-19T09:22:00Z",
    category: ["analysis"],
    source: "AFAD",
  },
  {
    id: "13",
    title: "İstanbul’da Toplu Taşıma Ücretlerine Zam",
    snippet: "İstanbul'da toplu taşıma ücretlerine zam yapıldı.",
    content:
      "İstanbul Büyükşehir Belediyesi, toplu taşıma ücretlerine yüzde 20 oranında zam yapıldığını açıkladı.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-19T07:10:00Z",
    category: ["latest"],
    source: "Hürriyet",
  },
  {
    id: "14",
    title: "Yeni Sanat Sergisi Kadıköy’de Açıldı",
    snippet: "Kadıköy’de çağdaş sanat sergisi ziyaretçilerini bekliyor.",
    content:
      "Kadıköy’de açılan yeni çağdaş sanat sergisi, yerli ve yabancı sanatçıların eserlerini bir araya getiriyor. Sergi bir ay boyunca ziyaretçilere açık olacak.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-18T16:35:00Z",
    category: ["latest", "experts"],
    source: "ArtNews",
  },
  {
    id: "15",
    title: "Ege Denizi’nde 4.6 Büyüklüğünde Deprem",
    snippet: "Ege Denizi açıklarında deprem meydana geldi.",
    content:
      "Ege Denizi’nde sabah saatlerinde 4.6 büyüklüğünde deprem kaydedildi. AFAD, depremin merkez üssünü Aydın açıkları olarak açıkladı.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-18T06:11:00Z",
    category: ["latest", "analysis"],
    source: "AFAD",
  },
  {
    id: "16",
    title: "Dünya Kupası’nda Şampiyon Arjantin",
    snippet: "Dünya Kupası finalinde Arjantin mutlu sona ulaştı.",
    content:
      "Dünya Kupası finalinde Arjantin, rakibini penaltılarla mağlup ederek şampiyonluğa ulaştı. Tüm dünyada büyük sevinç yaşandı.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-17T21:19:00Z",
    category: ["latest"],
    source: "Reuters",
  },
  {
    id: "17",
    title: "Borsa İstanbul Haftayı Yükselişle Kapattı",
    snippet: "BIST 100 endeksi haftayı rekor seviyede kapattı.",
    content:
      "Borsa İstanbul'da BIST 100 endeksi, haftanın son işlem gününü rekor bir seviyede tamamladı. Ekonomistler yatırımcıları dikkatli olmaya çağırdı.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-17T17:00:00Z",
    category: ["experts", "analysis"],
    source: "Bloomberg HT",
  },
  {
    id: "18",
    title: "Depremzede Çocuklar İçin Psikososyal Destek",
    snippet: "Depremzede çocuklara ücretsiz psikososyal destek veriliyor.",
    content:
      "Deprem bölgesinde yaşayan çocuklara yönelik psikososyal destek programları başlatıldı. Uzmanlar, çocukların yaşadığı travmanın en aza indirilmesi için ailelere de destek sağlıyor.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-16T14:00:00Z",
    category: ["experts", "analysis"],
    source: "AFAD",
  },
  {
    id: "19",
    title: "Antalya’da Orman Yangını",
    snippet: "Antalya’da çıkan orman yangını kontrol altına alındı.",
    content:
      "Antalya'nın Manavgat ilçesinde başlayan orman yangını, ekiplerin yoğun çalışması sonucu kontrol altına alındı. Yangında bazı tarım arazileri zarar gördü.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-16T10:44:00Z",
    category: ["latest", "experts"],
    source: "NTV",
  },
  {
    id: "20",
    title: "Mars’ta Deprem Kaydedildi",
    snippet: "NASA, Mars yüzeyinde bir deprem tespit etti.",
    content:
      "NASA’nın InSight uzay aracı, Mars yüzeyinde şimdiye kadar kaydedilmiş en büyük depremi tespit etti. Bilim insanları bu verinin gezegenin yapısı hakkında önemli ipuçları verdiğini açıkladı.",
    image: "https://picsum.photos/300/200",
    created_at: "2025-06-15T08:50:00Z",
    category: ["experts", "analysis"],
    source: "NASA",
  },
];

export const earthquakes: Earthquake[] = [
  {
    id: "1",
    provider: "AFAD",
    title: "İzmir - Seferihisar",
    date: "2025-06-27T08:32:00Z",
    mag: 4.8,
    depth: 10.2,
    longitude: 27.1428,
    latitude: 38.4192,
    region: "Ege Bölgesi",
    faultline: "Güney Ege Fay Hattı",
  },
  {
    id: "2",
    provider: "Kandilli",
    title: "İstanbul - Marmara Denizi",
    date: "2025-06-26T19:55:00Z",
    mag: 3.9,
    depth: 7.5,
    longitude: 28.5,
    latitude: 40.8,
    region: "Ege Bölgesi",
    faultline: "Güney Ege Fay Hattı",
  },
  {
    id: "3",
    provider: "AFAD",
    title: "Van - Tuşba",
    date: "2025-06-25T14:20:00Z",
    mag: 4.2,
    depth: 12.1,
    longitude: 43.379,
    latitude: 38.5012,
    region: "Doğu Anadolu Bölgesi",
    faultline: "Ağrı Fayı",
  },
  {
    id: "4",
    provider: "Kandilli",
    title: "Ankara - Çankaya",
    date: "2025-06-25T09:00:00Z",
    mag: 3.5,
    depth: 8.3,
    longitude: 32.8597,
    latitude: 39.9334,
    region: "Orta Anadolu Bölgesi",
    faultline: "Çankırı Fayı",
  },
  {
    id: "5",
    provider: "AFAD",
    title: "Antalya - Manavgat",
    date: "2025-06-24T22:11:00Z",
    mag: 4.0,
    depth: 15.0,
    longitude: 30.7133,
    latitude: 36.8969,
    region: "Akdeniz Bölgesi",
    faultline: "Alanya Fayı",
  },
  {
    id: "6",
    provider: "Kandilli",
    title: "Bursa - Gemlik",
    date: "2025-06-24T17:40:00Z",
    mag: 3.7,
    depth: 9.8,
    longitude: 29.061,
    latitude: 40.1956,
    region: "Marmara Bölgesi",
    faultline: "Gemlik Fayı",
  },
  {
    id: "7",
    provider: "AFAD",
    title: "Adana - Seyhan",
    date: "2025-06-23T12:00:00Z",
    mag: 4.3,
    depth: 11.2,
    longitude: 35.3213,
    latitude: 37.0025,
    region: "Akdeniz Bölgesi",
    faultline: "Adana Fayı",
  },
  {
    id: "8",
    provider: "Kandilli",
    title: "Erzurum - Palandöken",
    date: "2025-06-22T16:10:00Z",
    mag: 3.8,
    depth: 13.4,
    longitude: 41.2769,
    latitude: 39.9043,
    region: "Doğu Anadolu Bölgesi",
    faultline: "Palandöken Fayı",
  },
  {
    id: "9",
    provider: "AFAD",
    title: "Samsun - İlkadım",
    date: "2025-06-21T10:00:00Z",
    mag: 3.6,
    depth: 10.0,
    longitude: 36.3308,
    latitude: 41.2867,
    region: "Karadeniz Bölgesi",
    faultline: "Samsun Fayı",
  },
  {
    id: "10",
    provider: "Kandilli",
    title: "Gaziantep - Şahinbey",
    date: "2025-06-20T22:50:00Z",
    mag: 4.1,
    depth: 14.7,
    longitude: 37.3833,
    latitude: 37.0662,
    region: "Güneydoğu Anadolu Bölgesi",
    faultline: "Gaziantep Fayı",
  }
];